### ISSUE TITLE
To-do list for 0.2 launch

### ISSUE THREAD

**Issue by jacksonrakena** [jacksonrakena/circumstellar#1]
**To-Do List for Circumstellar 0.2**
- [ ] Logging system fully implemented with customizable logging outputs
- [ ] All guild, channel and message-related events completed and usable
- [ ] All guild, channel and message-related models completed, documented and usable
